name: Server CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint:eslint
      
      - name: Run tests
        run: npm run test

      - name: Upload coverage
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Coverage
          path: coverage/*
          if-no-files-found: error
      
      - name: Run express build
        run: npm run build:express
      
      - name: Upload express
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Express
          path: dist/*
          if-no-files-found: error

      - name: Run AWS build
        run: npm run build:aws

      - name: Upload AWS
        uses: actions/upload-artifact@v2.2.0
        with:
          name: AWS
          path: dist/*
          if-no-files-found: error
      
      - name: Run documentation build
        run: npm run build:documentation
      
      - name: Upload documentation
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Documentation
          path: docs/*
          if-no-files-found: error

