name: Server CI
on:
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install dependencies
        run: npm ci

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: | 
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Load Cache
        id: load-cache
        uses: actions/cache@v2
        with:
          path: | 
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run lint
        run: npm run lint:eslint
      
      - name: Run tests
        run: npm run test

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: coverage/*
          if-no-files-found: error
          retention-days: 1
  build-dev:
    runs-on: ubuntu-latest
    needs: setup
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Load Cache
        id: load-cache
        uses: actions/cache@v2
        with:
          path: | 
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run express build
        run: npm run build:express
      
      - name: Upload express
        uses: actions/upload-artifact@v2
        with:
          name: Express
          path: dist/*
          if-no-files-found: error
          retention-days: 1

      - name: Run AWS build
        run: npm run build:aws

      - name: Upload AWS
        uses: actions/upload-artifact@v2
        with:
          name: AWS
          path: dist/*
          if-no-files-found: error
          retention-days: 1
      
      - name: Run documentation build
        run: npm run build:documentation
      
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs/*
          if-no-files-found: error
          retention-days: 1
  build-prod:
    runs-on: ubuntu-latest
    needs: setup
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Load Cache
        id: load-cache
        uses: actions/cache@v2
        with:
          path: | 
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run express build
        run: npm run build:express
      
      - name: Upload express
        uses: actions/upload-artifact@v2
        with:
          name: Express
          path: dist/*
          if-no-files-found: error
          retention-days: 14

      - name: Run AWS build
        run: npm run build:aws

      - name: Upload AWS
        uses: actions/upload-artifact@v2
        with:
          name: AWS
          path: dist/*
          if-no-files-found: error
          retention-days: 14
      
      - name: Run documentation build
        run: npm run build:documentation
      
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs/*
          if-no-files-found: error
          retention-days: 14
