name: Server CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint:eslint
      
      - name: Run tests
        run: npm run test
      
      - name: Run express build
        run: npm run build:express
      
      - name: Run documentation build
        run: npm run build:documentation
        
      - name: Upload express
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Express
          path: dist/*
          if-no-files-found: error
      
      - name: Upload documentation
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Documentation
          path: docs/*
          if-no-files-found: error
      
      - name: Upload coverage
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Coverage
          path: coverage/*
          if-no-files-found: error
